BalticHack/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('citizenopinion.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

citizenopinion/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = "citizenopinion"
urlpatterns = [
    path('<city>', views.FilterCity.as_view(), name='filter_index'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
]

accounts/models.py
from django.db import models

citizenopinion/models.py
# -*- coding:utf-8 -*-
from django.utils import timezone
from django.conf import settings
from django.db import models
import datetime
from django.contrib.auth import get_user_model

User = get_user_model()


class City(models.Model):
    title = models.CharField(max_length=32)

    def __str__(self):
        return self.title


class Post(models.Model):
    title = models.CharField(max_length = 200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to = './', null = True)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title


class Poll(models.Model):
    question = models.CharField(max_length=200)
    post = models.OneToOneField(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.question


class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes_count = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Votes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    @classmethod
    def create(cls, user, choice):
        vote = cls(user=user, choice=choice)
        return vote

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

citizenopinion/views.py
#-*- coding: utf-8 -*-
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views import generic
from .models import Choice, Post, Poll, Votes, City
from django.contrib.auth import get_user_model

User = get_user_model()


class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'posts'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context.update({
            'posts': Post.objects.all(),
            'cities': City.objects.all(),
        })
        return context

    def get_queryset(self):
        return Post.objects.all().order_by('-create_date')


class FilterCity(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'posts'

    def get_context_data(self, **kwargs):
        context = super(FilterCity, self).get_context_data(**kwargs)
        context.update({
            'posts': Post.objects.filter(city=self.city).order_by('-create_date'),
            'cities': City.objects.all(),
        })
        return context

    def get_queryset(self):
        self.city = get_object_or_404(City, title=self.kwargs['city'])
        return Post.objects.filter(city=self.city).order_by('-create_date')


class DetailView(generic.DetailView):
    model = Post
    template_name = 'detail.html'


class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'results.html'


def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
        user = request.user
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        votes = Votes.objects.filter(user=user)
        if votes:
            user_polls = []
            need_to_add = False
            for v in votes:
                user_polls.append(v.choice.poll)
            if p not in user_polls:
                need_to_add = True
            if need_to_add:
                new_vote = Votes.create(user, selected_choice)
                new_vote.save()
                selected_choice.votes_count = Votes.objects.filter(choice=selected_choice).count()
                selected_choice.save()
            return HttpResponseRedirect(reverse('citizenopinion:results', args=(p.id,)))
            # return render(request, 'detail.html', {
            #     'post': p.post,
            #     'error_message': "You cant vote anymore",
            # })
        else:
            new_vote = Votes.create(user, selected_choice)
            new_vote.save()
            selected_choice.votes_count = Votes.objects.filter(choice=selected_choice).count()
            selected_choice.save()
        # selected_choice.votes += 1
        # selected_choice.save()

        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('citizenopinion:results', args=(p.id,)))

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>BalticSeaHack</title>
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
      <link rel="shortcut icon" href="{% static 'img/fav.png' %}" />
  </head>
  <body>

    
    <nav class="shdw navbar navbar-expand-lg navbar-default fixed-top" style="background: #3f51b5">
        <a class="navbar-brand text-light" style="margin-left: 5%; padding-left:-20%; " type="dissable"><img src="{% static 'img/logo.png' %}" width="30px" height="30px" alt="logo" style="margin-top: -5px;"> BalticSeaHack</a>
        <div class="container">
          <ul class="navbar-nav" style="margin-left: -7%;">
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'citizenopinion:index' %}" >Главная</a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-light" href="#" id="navbardrop" data-toggle="dropdown">
                Города
              </a>
              <div class="dropdown-menu">

                {% for city in cities %}
                    <a class="dropdown-item" href="{% url 'citizenopinion:filter_index' city.title%}">{{ city.title }}</a>
                {% endfor %}
              </div>
            </li>
      
        </ul>
        </div>
      <div class=" text-light" style="margin-top: 10px;  padding-bottom: -15px;">
        {% if user.is_authenticated %}
        <small style="font-size: 18px;">Hi {{ user.username }}!
          <a href="{% url 'logout' %}" class="btn btn-dark" style="margin-left: 10px; margin-top: -5px;">Log out</a></small>
      {% else %}
          <small style="font-size: 18px;">You are not logged in.
          <a href="{% url 'signup' %}" class="btn btn-dark" style="margin-left: 10px; margin-top: -5px;">Sign up </a>
          <a href="{% url 'login' %}" class="btn btn-dark" style="margin-left: 10px; margin-top: -5px;">Log In</a></small>
      {% endif %}
      </div>
      </nav>
      <br>
      <br>
      <br>
      <br>
      <br>
{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="shdw container jumbotron">
  <div class="row">
      {% if request.path == 'http://127.0.0.1:8000/1/vote/' %}
    <img  class="col-lg-6" src="../../media/{{ post.image }}" width="100%">
      {% else %}
      <img  class="col-lg-6" src="../media/{{ post.image }}" width="" style="height: 120%;">
      {% endif %}
    <div class="col-lg-6">
    <h2>{{ post.title }}</h2>
    <p>{{ post.text }}</p>
<!--    <a href="#" class="shdw btn btn-light" style="background: #ffffff; margin-top: 5%"><img src="thumb_up-24px.svg" width="32">  <b class="counter">21</b></a>-->

<!--    <a href="#" class="shdw btn btn-light" style="background: #ffffff; margin-left: 8px;margin-top: 5%"><img src="thumb_down-24px.svg" width="32"><b class="counter">42</b></a>-->

    </div>
  </div>
</div>
<br>
<br>
<br>
<br>

{% if user.is_authenticated %}
<h1 style="margin-left: 20%;">{{ post.poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div class="shdw container" style="margin-left: 20%; width: 100%;" >
  <form action="{% url 'citizenopinion:vote' post.poll.id %}" method="post">
  {% csrf_token %}
  {% for choice in post.poll.choice_set.all %}
     <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
     <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
  {% endfor %}
  <input class="btn bnt-dark" type="submit" value="Проголосовать" />
  </form>
  <br>
    
</div>
  <br>
  <br>
  <br>
  <br>
{% else %}
<div class="container">

    <div class="shdw card" style="width:100%; margin-left: ;">
        <h1 style="padding-left: 40px; margin-left: 2px;">{{ post.poll.question }}</h1>
        <ul class="counter " style="list-style-type:none; font-family:  sans-serif;">
        {% for choice in post.poll.choice_set.all %}
            <li>{{ choice.choice_text }} (Количество проголосовавших: {{ choice.votes_count }})</li>

        {% endfor %}
        </ul>
</div>
</div>
<br>
<br>
<br>
<br>
{% endif %}

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if posts %}
{% for post in posts %}
<div class="container">
  <div class="row">
  <div class="col-lg-2"></div>
  <div class="col-lg-8 " style="">
    <a style="color: #3f51b5;text-decoration: none;" href="{% url 'citizenopinion:detail' post.id %}"><h2>{{ post.title }}</h2></a>
    <div class="shdw card" style="width:100%">
      <img class="card-img-top" src="media/{{ post.image }}" alt="Card image" style="width:100%">
      <div class="card-body">
        <p class="card-text" style="overflow: hidden; height: 100px;">{{ post.text }}</p>
      </div>
    </div>
    </div>
  </div>
  <br>
  <br>
</div>
{% endfor %}
{% else %}
    <p>No posts are available.</p>
{% endif %}

{% endblock %}

templates/results.html
{% extends 'base.html' %}

{% block content %}

<div class="shdw container" style="padding-left: 0px; padding-right: 0px;">
        <h2 style="padding-top: 10 px;margin-top: 10px;">{{ poll.question }}</h2>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Вариант ответа</th>
              <th>Кол-во проголосовавших</th>
              
            </tr>
          </thead>
          
          <tbody>
                {% for choice in poll.choice_set.all %}
            <tr>
              <td>{{ choice.choice_text }}</td>
              <td>{{ choice.votes_count }}</td> 
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <a class="btn btn-light text-white" style="background-color: #3f51b5;font-size: 18px; width: 100%; border: 0px; margin-top: 10px;" href="{% url 'citizenopinion:detail' poll.id %}">Назад</a>

<br>    
    </div>
    
      
<!-- 

<div class="container">
    
    <div class="shdw card" style="width:50%; margin-left:23% ;">
        <h1>{{ poll.question }}</h1>
        <ul class="counter " style="list-style-type:none; font-family:  sans-serif;">
        {% for choice in poll.choice_set.all %}
            <li>{{ choice.choice_text }} (Количество проголосовавших: {{ choice.votes_count }})</li>
         
        {% endfor %}
        </ul>
    
<a class="btn btn-light text-white" style="background-color: #3f51b5;font-size: 18px; width: 100%; border: 0px; margin-top: 10px;" href="{% url 'citizenopinion:detail' poll.id %}">Назад</a>
</div>
</div> -->
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}

<div class="container " style="margin-left: 25%;">    
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>
</div>

{% endblock %}